---
- name: Getting files
  hosts: planetexpress   # run against the entire planetexpress group
  connection: ssh        # use the connection module, ssh.py (this is the default)
  gather_facts: no       # do not run the module, setup.py, to define ansible_facts

  tasks:
  - name: "Download virus protection software to install on hosts"
    get_url:
      url: https://api.kanye.rest/
     dest: ~/test.txt 
