---
- name: making dirs
  hosts: bender
  connection: ssh
  gather_facts: no

  vars: 
    nineties:
      - Teenage
      - Mutant
      - Ninja
      - Turtles
      
  tasks:

  - file:
      path: "{{item}}"
      state: directory
    loop: "{{ nineties }}"
